### ISSUE TITLE
Possible to use metadata directly instead of shimming all decorators?

### ISSUE THREAD

**Issue by kbirger** [GuidionDev/inversify-express-doc#2]
It seems like instead of creating all new decorators and introducing a tight coupling, this library could use the metadata created by inversify-express-utils and generate all of the same data. 

This would make it so you don't have to replace all of your decorators in order to use the package.

**Comment by Rawne** [comment]
Hey @kbirger ! Thanks for your suggestion, i will look into that, i'll have to see if it has all the data i need, but i agree it would be cleaner.
